name: Python Flask Docker build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docker-build:
    runs-on:ubuntu

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      
    
   
    - name: Build Docker Image
      run: docker build -t siddhesh776 /github_action_docker:latest .
   
    - name: Push Docker Image
      run: docker push siddhesh776/github_action_demo1:tagname
      
